version: '3.8'
services:
  scrpr:
    image: scrpr:latest
    build: .
    env_file: .env
    restart: always
    depends_on:
      - webdriver
    links:
      - webdriver
  webdriver:
    image: selenium/standalone-firefox
    container_name: selenium
    expose: 
      - 4444
